# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e4afeadde3d90c517490c3f4b35927ccc64500c585dcfadbf1b378b342dfa1b98f26a262d1d05f7d997c9859dd200794bfa4f715493f317c996b0d1bde24889

test:
  secret_key_base: e7ac3d1811067f4e70ed7fbc8c5f470d708855539d9e035f72a640b802a25c11af3502ff7e722e5347055e254a78b0d8c012427f87aa2c056acf6cb554d33360

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
